spring:
  application:
    name: ecommerce-app

  datasource:
    url: jdbc:h2:mem:ecommercedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

---
# Profile: dev (port 8080)
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8080

---
# Profile: staging (port 9090)
spring:
  config:
    activate:
      on-profile: staging

server:
  port: 9090

---
# Profile: prod (port 7070)
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 7070
